export const JWT_TOKEN_EXPIRATION = {
  ACCESS_TOKEN_EXPIRATION: '1d',
  REFRESH_TOKEN_EXPIRATION_REMEMBERED: '30d',
  REFRESH_TOKEN_EXPIRATION_SESSION: '1d',
  VERIFICATION_TOKEN_EXPIRATION: '1d'
} as const;

export const USER_ROLE = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  USER: 'USER',
} as const;

export const CUSTOMERS_SEARCH = {
  PAGE_NUMBER: 1,
  LIMIT: 5,
} as const;

export const PAGE = 1;
export const LIMIT = 10;
